version: "3.2"

services:
  db:
    image: mysql
    container_name: test_alpha_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - test_alpha_data_mysql:/var/lib/mysql
    networks:
      - test_alpha_network

  webserver:
    image: altimofeev/nginx-simple
    container_name: test_alpha_webserver
    working_dir: ${WORKDIR}
    ports:
      - ${APP_PORT}:80
    depends_on:
      - db
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/localhost.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/data/localhost
      - test_alpha_sock:${SOCKET_DIR}
    networks:
      - test_alpha_network

  app:
    image: altimofeev/php8.0-fpm
    depends_on:
      - db
    env_file:
      - .env
    working_dir: ${WORKDIR}
    volumes:
      - ./backend:/data/localhost
      - test_alpha_sock:${SOCKET_DIR}
    networks:
      - test_alpha_network

  frontend:
    build:
      context: ./frontend
    container_name: test_alpha_frontend
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    networks:
      - test_alpha_network
#    command: npm run serve

volumes:
  test_alpha_sock:
  test_alpha_data_mysql:

networks:
  test_alpha_network:
